---
#ConfgMap to setup parameters for user workload monitoring.
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |
    prometheus:
      # retention: 15d
      enforcedSampleLimit: 50000
      # enforcedLabelLimit: 500 
      # enforcedLabelNameLengthLimit: 50 
      # enforcedLabelValueLengthLimit: 600 
      externalLabels:
        smartops_source: user-workload-monitoring
        smartops: newton
      remoteWrite:
        - url: "http://prometheus-kafka-adapter.prom-kafka-adapter.svc.cluster.local:8080/receive"
          writeRelabelConfigs:
          - sourceLabels:
            - __tmp_openshift_cluster_id__ 
            targetLabel: cluster_id 
            action: replace 
          - sourceLabels: [__name__]
            # https://github.com/sustainable-computing-io/kepler/blob/424d2f88d2c050a354c023e8b830afefd312baf4/pkg/collector/collector.go#L28-L43
            regex: "pod_(.*)|node_(.*)"
            #regex: "node_energy_stat|pod_energy_stat|node_hwmon_energy_joule_total|node_cpu_scaling_frequency_hertz|node_package_energy_millijoule|pod_cpu_cpu_time_us"
            #regex: 'node_cpu* | node_hwmon* | node_intr_total | node_load* | node_memory* | kube_pod_info | kube_node_container* | kube_node_status*'
            action: keep
    # thanosRuler:
    #   retention: 15d



